### ISSUE TITLE
Hello, how are you?

### ISSUE THREAD

**Issue by paufau** [simon-82/ModVarietyPack#1]
The colonists refused to produce the glass. How to fix it?

**Comment by simon-82** [comment]
This should be fixed in the latest version. 
You tried it with version 1.01 of the modpack, right?

**Comment by paufau** [comment]
No, I try with modpack 1.0.
04 нояб. 2015 г. 4:37 пользователь "simon-82" notifications@github.com
написал:

**Comment by BorealisPhoenix** [comment]
Heh I spent all night trying to figure out what the issue was and found out it was sand and the bauxite got screwed up and can on to tell you and you fixed it already. hehe nice work.
