### ISSUE TITLE
Getting multipule weapons when killing raiders

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#101]
When killing raiders, they have their equipped weapon, and many are carrying in their inventory other weapons. Some carry a syringe, some carry grenades, some carry both, others have additional clubs.  Is this intentional? and this is with 1.23b

**Comment by simon-82** [comment]
Nothing related to raiders has changed. Only the storyteller fix.
Has this happened before? Which faction?

**Comment by TLHeart** [comment]
It is not the raiders after further hunting down what is going on... it is all the visitors have additional items in their inventory, including weapons... I will have to do more testing to see if it is the interactions of the mod pack, or the hospitality mod that is doing this. 

I suspect the hospitality mod, as the visitors will occasionally drop silver or loot if they liked their stay.

**Comment by TLHeart** [comment]
Yes the extra items are so the visitors can pay for their stay, from the hospitality mod... Can become a very good source of sliver and weapons.
