### ISSUE TITLE
pawn head not found error

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#104]
getting this error when loading a save file. Game does play on.

Tried to get pawn head at path Things/Pawn/Humanlike/Heads/Male/Male_Narrow_Normal-Scar1 with color RGBA(0.949, 0.929, 0.878, 1.000) that was not found. Defaulting...

(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

Tried to get pawn head at path Things/Pawn/Humanlike/Heads/Male/Male_Narrow_Normal-Scar1 with color RGBA(0.340, 0.320, 0.300, 1.000) that was not found. Defaulting...

**Comment by simon-82** [comment]
Head mod is still very new. Not sure why it is even looking for that head. The file is not needed. Added it anyway now. Maybe it wants equal options for different heads.

**Comment by simon-82** [comment]
After more testing I think the error is kinda random. Even with those textures added, it then jumps to another head sometimes. I believe it is related to females and males having different heads now, which is not something the vanilla game has. The error is non-critical.

**Comment by TLHeart** [comment]
It may be non critical, but it is still an error, that you needed to be aware of. 

And random errors, can cause other problems with other parts of the game, especially since you are having to do a detour method to even get it to work.
