### ISSUE TITLE
Started new colony with 124. no cleaning icons missing.

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#106]
Started new colony with 124, and I have no ability to clean... the no cleaning icons are missing... so I save, and reload, which gives me the no cleaning icons, but then I get this error;

Exception in LookDictionary: System.ArgumentException: An element with the same key already exists in the dictionary.

  at System.Collections.Generic.Dictionary`2[Verse.ResearchProjectDef,System.Single].Add (Verse.ResearchProjectDef key, Single value) [0x00000] in <filename unknown>:0 

  at Verse.Scribe_Collections.LookDictionary[ResearchProjectDef,Single](System.Collections.Generic.Dictionary`2& dict, System.String label, LookMode keyLookMode, LookMode valueLookMode) [0x00000] in <filename unknown>:0 

and then this;

Could not resolve reference to object with loadID Colony661896234 of type RimWorld.Faction. Was it compressed away, destroyed, had no ID number, or not saved/loaded right?

[output_log.txt](https://github.com/simon-82/ModVarietyPack/files/83869/output_log.txt)

**Comment by Karel-Kroeze** [comment]
These two are completely unrelated (albeit both CCL). Both sometimes can happen when changing mods without restarting the game, is that what you did? 

Fyi, any time you change mods you should restart the game to avoid any number of weird bugs.

**Comment by TLHeart** [comment]
I always restart whenever anything is changed. This happened with the very first start... clean vanilla rimworld, started, exited, moved mods to mod folder from download. moved config file to config file, started the game... had no cleaning icons... saved game exited restarted game, and got the next error message, so NO I had not changed anything.

**Comment by simon-82** [comment]
I must agree to what Fluffy said. Must have been some issue with mods not loading properly. 
Can't reproduce that error by myself. 
Closed for now.
