### ISSUE TITLE
Inability to kill (shoot) starving/angered animals, GUI disappears upon mouse-over

### ISSUE THREAD

**Issue by Crupellarius** [simon-82/ModVarietyPack#107]
The title almost explains it best. I have had extreme difficulty trying to play this mod due to this issue, once I get far enough with my colony there will be regular attacks by starving boars/tarantulas/et cetera, and my colonists are unable to attack. I am not sure why, but once I draft a colonist with a ranged weapon, and then move my mouse over to the target I wish for them to shoot at, my entire GUI vanishes (all of the tabs at the bottom, the information on the character in the lower left, the colonist tags on the top of the screen, and the box that would have appeared that allows me to choose how I want to attack, i.e. melee attack the creature or fire at the creature. I have looked through the list of previous bugs, and had found no mention of anything like this, and, it has led me to only be able to play the game with animals turned off. Now, I am not sure how exclusive this problem is to attacking creatures, since I have also encountered the same exact problem when trying to attack prisoners (with ranged) during the initial stages of the game during the crash landing mod's intro. And extension of that account is that my colonists, when drafted, would not automatically open fire on nearby targets. The problem has been confirmed by the Youtuber named Blitzkriegsler in one of his videos, it is mentioned very early on: 

https://www.youtube.com/watch?v=yE8mM6RW1ak&index=3&list=PL4D232HeetQMG_053Muk7PnU36f3eaqCQ 

I will be trying to troubleshoot on my own, but I can only admit that this issue has been a major drag on the mod's playability, although there is so much potential.

**Comment by simon-82** [comment]
I am not sure if this is the right modpack you are referring to. 
The video link you posted uses the Hardcore SK modpack. And you talk about tarantulas, which are also not in my modpack. 
This is NOT the Hardcore SK modpack and I never had a similar problem. 
If you are indeed playing with my modpack and are having this bug, I need your output:log and your savegame.
