### ISSUE TITLE
missing face sprites and moved body sprites

### ISSUE THREAD

**Issue by Shikareth** [simon-82/ModVarietyPack#108]
Well, something is wrong with colonist body display. "Reinstal" hadn't fix it.
Screen:
![bug](https://cloud.githubusercontent.com/assets/16690152/12303430/8f81f2e4-ba2a-11e5-9e59-90cdc0fe02b3.png)

**Comment by simon-82** [comment]
lol. Looks funny. Try following the instructions on the wiki. I don't have this issue.
If you are sure you did everything right, send me the save file and I take a look.
