### ISSUE TITLE
Glass table not usable by colonists as a table

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#109]
Don't know if you want the glass table to actually be usable as a table to eat at by the colonist. In its current def it is a pretty piece of furniture. Colonist will not gather at it or eat at it. I like the looks of the glass table, and have been building them on the porches of my houses, for the colonist to enjoy their morning meal at, but I had to change the def for that to happen. 

I changed  "ThingDef ParentName="FurnitureBase"
    defName GlassTableShort defName

to    ThingDef ParentName="TableBase" 
    defName GlassTableShort defName

Just a small change

Otherwise I had to use the modular table.

Screenshot of my present colony.

![screenshot 29](https://cloud.githubusercontent.com/assets/15680072/12338168/a45c3994-bacb-11e5-80bc-690bf3ab6e57.png)

**Comment by simon-82** [comment]
Ah I see. Good suggestion. 
I remember changing the glass table. I used it in bedrooms as a side table for beds. That was before I had your nice EndTable. The problem I had was that as a regular table it has the xml tag "gathering spot". So the colonists go into a bedtoom randomly and "relax socially" at these tables (1x1 table, so alone... very social... lol). 

I see you build porches just like MidnightSnackGames on YouTube. I like his videos, too. :stuck_out_tongue_winking_eye:

**Comment by TLHeart** [comment]
Understand why you made the change... And yes I liked how the porches looked so I copied the idea. And that is why I rejected the idea of the colonists being able to eat at the end table.

To prevent the other colonist from entering a bedroom, there is the do not disturb mod, that the colonist forbid their doors when alone in their room.

**Comment by simon-82** [comment]
After thinking about it, I will leave the glass table as a "a pretty piece of furniture" for now. 

Good idea with the do not disturb mod. I might add that.
