### ISSUE TITLE
Bug / Enhancement: Unable to install Organic (Natural) Arms

### ISSUE THREAD

**Issue by Owai-Seek** [simon-82/ModVarietyPack#110]
Unfortunately there is no "Shoulder" body part Growable or Harvestable), and arms do not install from the shoulder down, making it impossible to instal organic arms after a bionic one or prosthetic has been installed (as it replaces the shoulder) or if a colonist has a broken / missing shoulder.

There also seems to be no way to repair a Clavicle.

**Comment by simon-82** [comment]
Alright. After looking through the code for this I found all the prosthetics use left/right shoulder as root point to install them. Only the natural arms use left/right arm as root point. 

So should be easy enough to change the natural arms to also install from the shoulder. 
It was set like this in the EPOE mod. I didn't change it. So maybe there was a reason for this being that way. Not sure. Needs testing.

**Comment by simon-82** [comment]
Good news. Did the change and I was able to replace a bionic arm with a natural arm. Fix will be included in the next release. Might want to inform the original mod author of this :smile:
