### ISSUE TITLE
Loading Issue.

### ISSUE THREAD

**Issue by Moonshardai** [simon-82/ModVarietyPack#112]
Hello.

It appears i'm having an issue loading most saves with this mod. I'm not sure whats going wrong, however i instlled all correctly, even made sure to vanilla install everything including rimworld.

However if i close the game down for an extended period of time and try to load a save it will spew nothing but errors at me.

This is my output log below. it seems to be it can't find something?

I've tried other modpacks and this is the only one with this issue.

[output_log.txt](https://github.com/simon-82/ModVarietyPack/files/102085/output_log.txt)

**Comment by Moonshardai** [comment]
So i tried making a new colony. It does the same thing even when I save straight away. I think it's something with loading the mods because when i first played, no console popped up but this time it did.

**Comment by simon-82** [comment]
Thanks for the log. Yes it can't find anything, you are right. 
I never had this issue with loading a game, so make sure you follow the instructions on the wiki.
Especially you should close the game and restart it once all mods are loaded the first time. 
Saving and loading work fine for me. So it must be either an installation issue or an issue with mods not loading correctly. 
If you still have this issue send me the savegame (+which version of the pack it was saved with) and I take a look at it.
Closed for now.

**Comment by Moonshardai** [comment]
SUre thing. I do still have the save that i can send. Where would i best be to send it?

I followed the instructions to the letter twice over, hence why i made a log here.

Thanks ^,.,^.

**Comment by simon-82** [comment]
Doesn't matter. Google Drive? Dropbox? MediaFire? I don't know what you use. 
And the save is with the latest version?

**Comment by Moonshardai** [comment]
I used it with the latest Mod pack 1.24

[Bedias.zip](https://github.com/simon-82/ModVarietyPack/files/102299/Bedias.zip)

**Comment by simon-82** [comment]
Thanks :+1: I'll take a look

**Comment by Moonshardai** [comment]
I made two others as well with just the basic open the game, start coloney and then save, shut down. Hopefully this might be clear as well or narrow it down. 

[Colony1.zip](https://github.com/simon-82/ModVarietyPack/files/102301/Colony1.zip)
[Colony2.zip](https://github.com/simon-82/ModVarietyPack/files/102302/Colony2.zip)

**Comment by simon-82** [comment]
I can load all your saves without any error. 
Must be an installation issue

**Comment by Moonshardai** [comment]
Strange. Oh well. Thank you for the help ^.^. Wish i knew why it might've installed funny.

**Comment by Moonshardai** [comment]
Ok, i've tried new ways. Sorry to keep this up, it's driving me nuts. I didn't touch anything but install the mod as per instructions word for word. Then i opened it up 3 times, third time it had the error logs. I tried this three times over, always on the 3rd time. I checked through everything to find the below being the only difference between the Ok log's and the not ok logs.

Could not find a type named AdditionalLighting.Building_PathLamp

That is the only issue and maybe where my entire ting maybe falling apart. It seems that it cannot find the Additional Lighing Building Path, Yet i've checked and the .Dll is still in the mods folder. and it appears the file isn't different. as per below. Do you know which file directs it to look for that particular .dll?

<defName>Lighting_PathLamp</defName>
<label>Path light</label>
<thingClass>AdditionalLighting.Building_PathLamp</thingClass>
<category>Building</category>

It links to the Buildings_Furniture in the mod Variety pack folder > de f> ThingDefs.

**Comment by Moonshardai** [comment]
![rimworld error](https://cloud.githubusercontent.com/assets/16152998/12540095/34fa78a0-c367-11e5-960d-831fe070ca05.png)

Extra info from when i click the error.

**Comment by simon-82** [comment]
Hm, not sure about that.
3rd time? Why would it be loading any different the 3rd time than any other time? Makes no sense to me. 
Again, I can load your save games just fine. And loading my own saves also isn't a problem.

I don't really understand your question though. You already answered it yourself. The files are the additionallighting.dll and building_furniture.xml.
