### ISSUE TITLE
"cooked"/"raw" cannibalism

### ISSUE THREAD

**Issue by Flow86** [simon-82/ModVarietyPack#113]
Hi,

it seems that eating "bion meat" is marked as cannibalism? perhaps that meat shouldnt be marked to be "eatable" by default?

**Comment by simon-82** [comment]
Good suggestion :+1: 

I'll mark them with a "x" in the recipes that use meat. Just like the norbal and human meat. That is what you meant, right? Added in next release :smile:

**Comment by Flow86** [comment]
yes exactly. thx
