### ISSUE TITLE
Are early mechs op?

### ISSUE THREAD

**Issue by codingHahn** [simon-82/ModVarietyPack#116]
As I played, a mechanoid terraformer showed up. 
The Sythers have a range of 120. That's too op early on. And the Centepides with poor miniguns are not wasting any bullets. Every bullet hits. 

I think they're too much of a threat early on.

Difficulty: Rough

**Comment by simon-82** [comment]
1. There are different ways to deal with the terraformer. Not all require fighting the mechs.
2. They are not op, just need EMPs (grenades/mortars) or better tactics. 
   If you give scythers the range advantage, that's your fault tbh. Centipedes are already nerfed down from what they are in CombatRealism originally. They can be hard to deal with early, not impossible though

**Comment by codingHahn** [comment]
Ok, thx for the fast reply.
