### ISSUE TITLE
Packaged meal storing bug?

### ISSUE THREAD

**Issue by cst89** [simon-82/ModVarietyPack#119]
Hi, thanks again for a great work with mod update! 

I think I just found a storage bug in v1.25, check the picture. When hauling the spawned Survival packaged meals to the stockpile zone, pawn picks up just one of them (does not collect full stack as usual). After hauling it to the stockpile, the other items are blocked. I am unable to haul and stack other with the first placed item in the stockpile zone, even when I clearly have the zone allowed and it is not full. It says "No empty place configured to store... "

http://i.imgur.com/NmMEM0z.jpg

Thanks !

**Comment by cst89** [comment]
My bad, accidentally decreased the stockpile quality limit to 99 % while the items decayed a little. That's why it couldn't store it anywhere... :{ dumb topic closed.

**Comment by simon-82** [comment]
oh well, good you figured it out yourself :smile: 
I saw you forked the project. You plan on contributing? :octocat:

**Comment by cst89** [comment]
Sorry, I am not a modder myself :) But I would like to contribute somehow if possible, what would help you to proceed with this great work?
