### ISSUE TITLE
Enhancement: Cooking Stove takes too long to Research

### ISSUE THREAD

**Issue by Owai-Seek** [simon-82/ModVarietyPack#120]
I base in winter biomes, which means I have next to no time to plant crops and get plants for food, this is problematic, (but a necessity because that's the biome I chose.) Hunting is often done manually to cook jerky until something else can be arranged.

Crafting (for smelting and stone walls), Power, and Construction (for heat) are must-haves before the poor temperature conditions destroy a colony. Because of this, I learned the hard way that the Cook Stove is locked behind Agriculture 2 > Cooking 1. (I only normally only research into Agriculture when I need to fish, most of my colonies are founded on hunting for meat.)

As it stands now, you're required to research 3100 points JUST to cook simple meals, I haven't had a chance to try the food press, but even then you have to do 2100 points of research.

My solution would be to unlock the Cook Stove in Power 1 again, or at the very least let Power 1 lead to Cooking 1 instead of Agriculture 2, as it makes little to no sense for a cold or Cannibal colony to research into Agriculture until they can prevent themselves from freezing to death or going bonkers from the cold conditions and ugly environments.

**Comment by simon-82** [comment]
All good ponts. I understand your issues. CookStove is unlocked with Power I in 1.26 :+1:
