### ISSUE TITLE
colonist beds not getting assigned

### ISSUE THREAD

**Issue by Crusader2010** [simon-82/ModVarietyPack#122]
The colonist beds do not get assigned an owner by using the button "Set owner". In the description panel on the left the owner remains as "Nobody".

**Comment by simon-82** [comment]
Should actually work just like before. Didn't change anything related to that. Only thing that has changed related to beds are the materials needed to make a guest bed.
I'll take a look.

**Comment by lordmatiz** [comment]
@simon-82: I'm almost sure that Crusader2010 meant "Guest Beds". They are better than sleeping spot and cheaper than for example Cowskin Beds which makes them perfect for starting colony... however you cannot set ovnership of them - only colonist/prisoner/medical tabs.

**Comment by simon-82** [comment]
Oh, really? Well, guest beds shouldn't be assigned to colonists. They are meant for guests.
And the material cost is now adjusted to be the same like the hide beds. In the latest version that is.
