### ISSUE TITLE
prevent visitors taking over beds enhancement

### ISSUE THREAD

**Issue by Crusader2010** [simon-82/ModVarietyPack#123]
Can we have a way to prevent visitors from sleeping in certain beds (or to make them not available to guests)? I just can't find any way to do this :(

**Comment by Owai-Seek** [comment]
I'm fairly certain they only take over guest beds, and if not then any beds that are in a designated "Guest Room", which means a room with a guest bed in it.

**Comment by simon-82** [comment]
As @TheWhitePony said. The guest beds are there for a reason. They should prefer to sleep in those. If you don't have any guest beds at all, they don't sleep in a bed, as far as I know. They should actually just sleep on the ground. 
I'll take a look if there is something wrong though.
