### ISSUE TITLE
"Allow rotten" seemingly causing a bug 

### ISSUE THREAD

**Issue by magik20** [simon-82/ModVarietyPack#124]
I've noticed that when something is shown in the bill to "allow rotten" it seems to bug the job.

![2016-02-26 18_46_27-jump list for excel 2013](https://cloud.githubusercontent.com/assets/17505190/13367553/b6690666-dcb9-11e5-9036-5b739217b1aa.png)

**Comment by simon-82** [comment]
The _allow rotten_ doesn't need to be there. I could remove it.  
But what do you even mean with "bug the job"?
Any errors in the game? Errors In the log file? If there are errors, why do you think they relate to _allow rotten_?

**Comment by magik20** [comment]
I'm not 100% sure its the cause, not sure how best to track it.... however when i notice that a pawn isnt working on a project and i uncheck "allow rotten" it seems to get them working on the project....

**Comment by magik20** [comment]
I've also noticed that if a job has "allow rotten" in it, if i kill that one and start a new one, allow rotten is gone and the pawns start working on it.
