### ISSUE TITLE
Insane "organ harvested" mood debuff

### ISSUE THREAD

**Issue by username-password** [simon-82/ModVarietyPack#125]
I removed an arm from a colonist and immediately installed a upgraded bionic arm in the same slot. Colonist got -30 mood debuff for 15 days. Did it again on the other arm. -53 for 15 days. WTF?

**Comment by Owai-Seek** [comment]
You shouldn't have to cut off limbs to install bionics, it should already be available in the surgery list.

**Comment by username-password** [comment]
Yes, but the original arm is lost for some reason if I just install the bionic arm without removing the original arm first.

**Comment by simon-82** [comment]
Want the arm, deal with the mood debuff. Change the arm to bionic and loose the natural arm, less mood debuff.   

I don't know. Seems fair to me.

**Comment by username-password** [comment]
-30 / -53 is still insane. This is a guaranteed breakdown for every colonist, even with Sanguine + Iron Willed.

**Comment by Owai-Seek** [comment]
Then don't cut your own colonists limbs off? There's plenty of norbals and pirates attacking constantly.

**Comment by username-password** [comment]
Ok, limbs will remain attached ... for the time being.
