### ISSUE TITLE
Make list of compatible "addon" mods

### ISSUE THREAD

**Issue by Ristellise** [simon-82/ModVarietyPack#128]
Says what is on the tin.

**Comment by Owai-Seek** [comment]
"Using additional mods (not included in this modpack) is not recommended."

Beyond suggesting extra things be added to the pack, I see no reason as to why simon should have to support people using other mods within the pack.

Anything you add would need to be debugged by you.

**Comment by EPSIL0N** [comment]
Aside from things like skins, hairs and maybe some animals pretty much everything would require that additional mod to be modified to share the same resources and balances.

I am not sure if this or the thread is the place to discus the additional mods for consideration or asking people to make the mod work in the short term.
