### ISSUE TITLE
Industrial Coolers dont appear to be working

### ISSUE THREAD

**Issue by magik20** [simon-82/ModVarietyPack#130]
![rim](https://cloud.githubusercontent.com/assets/17505190/13510838/ea2a6590-e168-11e5-93e4-8bdfd4ad7291.png)

**Comment by Ristellise** [comment]
Is your room saying "unroofed" or is it ssyig it is in a room?

**Comment by Owai-Seek** [comment]
I'm almost 100% sure that the cooler is facing the wrong way, to my knowledge the Blue Box is meant to be in the room being cooled, not the other way around. Exhausts can fit on any face of the Industrial Cooler.

**Comment by Ristellise** [comment]
Yeah

**Comment by Ristellise** [comment]
Blue box is the area being cooled.

**Comment by magik20** [comment]
ah yes i screwed up... so maybe the real "Bug" is that you can mount the exhausts on the wrong side?

**Comment by Ristellise** [comment]
You placed it wrongly
![screenshot_2016-03-05-00-53-49](https://cloud.githubusercontent.com/assets/7894419/13533755/d42f9d1e-e26c-11e5-974d-a2da1545ae47.png)
The blue line is the cooling side. The red one is the heating side please look / study the picture carefully.

**Comment by magik20** [comment]
i double checked, you're right i had it placed wrong

the question is why was i able to place the exhaust units on the wrong side?

**Comment by Owai-Seek** [comment]
Because you can place the exhausts on any surface of the Cooler. I don't know why it was made that way, but it was. I don't see how you missed it because the cooled room is highlighted when placing any object that modifies temperature. This ticket should probably be closed now.
