### ISSUE TITLE
Empty Research Tab

### ISSUE THREAD

**Issue by GeniusLoci** [simon-82/ModVarietyPack#132]
The Research Tab is empty. I built a research bench, tab is still empty. Topic #103 was no help unfortunately. 

How can i help to solve this problem?

greetings!

**Comment by hohounk** [comment]
Same here. 

I extracted the main game to a new folder, installed the pack as was told in the readme file, ran the game via the created shortcut, created a new world/colony and ended up with empty research tab.

I'm not sure if it's important but the first time I opened the research tab was before I had completed the research bench. After quitting to menu and reloading, I got a few errors in devlog: http://i.imgur.com/snu6kDS.png

After closing the game completely and reopening, I got the research stuff visible but still a couple of errors in devlog:
http://i.imgur.com/2ZHHUc6.png

[edit]
Saved, restarted the game, loaded the same save again and no more errors and research is still visible. Not quite sure what caused the issue.
