### ISSUE TITLE
There is not any Cleaning area Zone

### ISSUE THREAD

**Issue by DanielAlex123** [simon-82/ModVarietyPack#134]
I have been searching and searching but there is no "Ckeaning Area" Zone to create, and i need o clean my base, is there the option to clean? or it is not?

**Comment by Owai-Seek** [comment]
There is most definitely a button to create a cleaning area zone, not 100% sure but I'd assume it's in Orders or Zones tab (sorry haven't played the game in a bit and i'm a little tipsy.) It looks like a dusting pan brush if that makes sense.
