### ISSUE TITLE
Mod Suggestions: Fix Bone and More Mechanoids

### ISSUE THREAD

**Issue by Owai-Seek** [simon-82/ModVarietyPack#135]
Fix Bone by Latta
https://ludeon.com/forums/index.php?topic=11171.msg111221#msg111221

Allows the creation of artificial bones that allow the repair / replacement of existing (but broken) bones. Makes it easier to fix and bring a colonist up to 100% efficiency without having to resort to bionics.

More Mechanoids by Orion
https://ludeon.com/forums/index.php?topic=9221.0

Adds 4 new Mechanoids the the game, seeing as how the Federation Mechs are basically just people with incredibly heavy armor, this mod adds some more mechs to the actual mech faction.

Each one seems to have a specialisation, which makes larger battles with mechs more unique instead of it just being Whoever gets shot with a Doomsday Rocket or High Powered Rifle first. (Looking at you Centipedes)

**Comment by EPSIL0N** [comment]
More Mechanoids sounds interesting, I know we have been tweaking ranged weapons and this adds one I think but I have no clue if we would also need to tweak the new melee weapons.

Fix Bone might need more tweaking or be impossible, I could have sworn we have EPOE rolled into MVP.

**Comment by Owai-Seek** [comment]
EPOE is in the modpack, but it doesn't include the Synthetic Organs portion of the mod (At least as far as I'm aware), EPOE also has no way to fix broken bones (You can craft new organs, but you can't repair broken parts inside the limb.)

As for the More Mechanoids, I believe ranged weapons are the only thing requiring a specific touch, because without that their projectiles would not be tailored to combat realism. I'm not 100% on that by the way.

I figured I would mention it because someone in the main Ludeon Studios thread mentioned it, and it seemed like a nice idea. (I try to play without a lot of turrets, kill boxes, or cheesing, so centipedes really make me mad.)
