### ISSUE TITLE
Plant texture Bug

### ISSUE THREAD

**Issue by Keldoo** [simon-82/ModVarietyPack#138]
There is a bug on most of the plant texture that can be solved by putting an upper case at the begginning of the png file in \Mods\ModVarietyPack\Textures\Plant (ex sugarcanePlant-> SugarcanePlant)
(yeah it's an easy one you probably already solved it. Keep up the good work !)

**Comment by simon-82** [comment]
There is no public release for A13. Why are you reporting this?
The latest commits clearly state that it is WIP. 
Once it is actually playable, I will release it. Right now, it is not.  

That being said, if you are interested in helping with the project come join the modding slack. 
I'm looking for someone to help :)
