### ISSUE TITLE
Not able to create a growing area

### ISSUE THREAD

**Issue by cody3647** [simon-82/ModVarietyPack#14]
Started a game, couldn't create growing area when I got to it.  Reinstalled Rimworld and mod pack and still couldn't create a growing area.  It shows the distances when I drag the mouse to create a zone, but there is no box when dragging or after.

No errors showing up in the log.

**Comment by TLHeart** [comment]
Need to go to architect, food, click on cultivate soil and improve the soil first, then you can create the grow zone.
