### ISSUE TITLE
Pawns stuck trying to determine job

### ISSUE THREAD

**Issue by Paragonid** [simon-82/ModVarietyPack#17]
Pawns do nothing/standing on thrown exception. (Sandra and Holiday)

![Error screenshot](http://i.imgur.com/HJEXcAU.jpg)
![Job table](http://i.imgur.com/kRH7rEk.jpg)

World saves
https://www.dropbox.com/s/qk5ynlf91mxufp3/SaveData%20-%20Copy.7z?dl=0

**Comment by simon-82** [comment]
Thanks for reporting. 
I am still investigating. So far I got them unstuck by going into outfits and allowing all.
They immediately get unstuck and setting theit outfit then to disallow all does not get them stuck again. 
Looks like they were looking for a specific piece of clothing that wasn't on the map for some reason.

**Comment by simon-82** [comment]
Alright, found the bug and fixed it. Will be included in next release. 
So long, if that error comes up again, set the outfit to allow all. This unstucks them. Then you can change it back.
