### ISSUE TITLE
Comparisson of grass in temperate forest.

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#19]
Here is the grass from another game.
![screenshot 15](https://cloud.githubusercontent.com/assets/15680072/11049643/0df3ed6e-86fd-11e5-8fc5-5b6785e97843.png)
and the grass from your version 1.12
![screenshot 16](https://cloud.githubusercontent.com/assets/15680072/11049654/2282a4dc-86fd-11e5-927c-9804747937d4.png)

**Comment by simon-82** [comment]
Try it with [this commit](https://github.com/simon-82/ModVarietyPack/commit/ef490ff3e64847dfcf1faf9a336929a65b417812). I think I got it fixed now

**Comment by TLHeart** [comment]
To put it to the stress test, here is the same 1.12 game after loading in your fix, 20 days later, same spot on the map. I now have native grass growing.

![screenshot 18](https://cloud.githubusercontent.com/assets/15680072/11051127/b7c52fcc-8709-11e5-9a44-3ddae6aa148d.png)

**Comment by simon-82** [comment]
Hopefully this is now enough grass. I leave the issue open for the time being. 
Need to test for longer time spans.

**Comment by simon-82** [comment]
seems ok.
