### ISSUE TITLE
Question; tailors loom

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#22]
Tailors loom is set to required tailoring as the work type. Makes sense to begin with. But all the recipes are set to crafting type. So the skill set on the table overrides the skill set by the bill, as a crafter can not work at the loom, must have tailoring enabled. I have a description on the recipe for recycle apparel that says it is a low level crafting job, but because that recipe is tied to the loom, it now requires a tailor to recycle apparel.  Do you want the description on the recycle apparel changed then?

**Comment by simon-82** [comment]
Wait, where is the tailors loom saying it needs tailoring? 
I can only see the recipes defining a worktype. And that is crafting.
Crafters should be able to work there. They will work faster if they are good at tailoring though

**Comment by TLHeart** [comment]
The workgiver defines it as tailoring. and that overrides what the loom says.

**Comment by simon-82** [comment]
Ah ok now I see what you mean. I think everything on that table should be crafting tbh. It's making cloth from raw ressources and in the case of recycling it's ripping stuff apart. 
Actually making clothes is what tailoring is to me. And that is what the tailor's bench is for.
