### ISSUE TITLE
Volume on added animals is LOUD

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#23]
I really really don't like the loud animal sounds from the new additions.They should be a background sound, not a make you jump out of your chair sound.

**Comment by simon-82** [comment]
The cats you mean? I can turn it down, no problem. Are you playing with headphones or something? Because I didn't notice it yet

**Comment by TLHeart** [comment]
Yes the roar of the cats, actually shook my desk. I do have  a sub woofer attached.I do wish Tynan had more options to control the sounds. 

```
 On Saturday, November 14, 2015 2:23 AM, simon-82 <notifications@github.com> wrote:
```

 The cats you mean? I can turn it down, no problem. Are you playing with headphones or something? Because I didn't notice it yet—

**Comment by simon-82** [comment]
ha, that's pretty funny. Angry lions are angry :stuck_out_tongue_winking_eye:

**Comment by TLHeart** [comment]
yea but he was my pet lion, he landed with me, so he roared often.

```
 On Saturday, November 14, 2015 4:50 AM, simon-82 <notifications@github.com> wrote:
```

 ha, that's pretty funny. Angry lions are angry  —
