### ISSUE TITLE
Recipe Problems

### ISSUE THREAD

**Issue by Zepher79** [simon-82/ModVarietyPack#24]
Hey there, noticed a pair of small inaccuracies with two recipes during my last playthrough.

The Industrial Cooler is created using Steel Ore instead of Steel bars. I assume this is unintended as every other temperature building uses bars.
The Adrenaline Rib recipe is set to use Platsteel Ore in the ingredients define, but Platsteel Bars in the fixedIngredientFilter define. This appears to make it impossible to make in game. I assume it is meant to use Platsteel Bars the same as all other bionic recipes.

One last thing related to recipes is that the Orbital Trade Beacon still uses Steel Ore instead of Bars, the same as Vanilla. That might not be a bug, but it does end up meaning the player must keep a reserve of Steel Ore instead of smelting it into bars. I'd personally prefer to simply have it use Bars for the sake of consistency and to avoid micromanagement.

**Comment by simon-82** [comment]
Nice findings! Thanks for the report! 
I noticed some recipe problems myself while playing / testing.
The other one I have found is realated to making simple meals out of the "cooking ingredients". 
You shouldn't be able to make a simple meal out of flour for example.
Just adding that here so I can fix them together.

Now for the trade beacon:
This one was left with steel ore on purpose, the others are clearly mistakes.
Now on harder biomes (ice sheet and other rough ones) you need to be able to trade FAST. 
If the beacon uses bars, it would take even longer to make. 
I understand your concern though. 
So having the beacon made out of bars wouldn't make it too hard for you early game on an ice sheet biome?

**Comment by Zepher79** [comment]
Ah, I can see why that is. Obviously the ability to survive trumps, it was just a small thing that was annoying is all.

One other odd thing I ran across was in trying to make a Drugged Rib and it threw an error when trying to use Beer to make it. The log said something to the effect of 'Beer is not a Stuff, changing to default,' at which point the bionic changed to 'Wooden Drugged Rib' while the colonist was working on it, and then could not finish it, it simply sat on the work bench at 0 work needed. Sorry if that's vauge, I'm not at my computer. I think it might be related to which material is used last, but I'm not sure.

**Comment by simon-82** [comment]
I look into it, thanks again :+1:

**Comment by simon-82** [comment]
all fixed
