### ISSUE TITLE
Something is missing.

### ISSUE THREAD

**Issue by BorealisPhoenix** [simon-82/ModVarietyPack#28]
Is their a possibility you could look into adding this mod or something like it into your mod pack?
https://ludeon.com/forums/index.php?topic=7112.0
i'd like to see some kind of recognition from the colonist that they are actually living with other people.

**Comment by simon-82** [comment]
I think Alpha 13 will add relationships, at least that is what Tynan posted.

**Comment by BorealisPhoenix** [comment]
How about Metal bars for a jail cell? can be shot through but can't be passed through?
Also it seems the medication turned into syringes is not working. they are becoming pistols

**Comment by simon-82** [comment]
good idea, I will think about that :+1: 
Note to self: Don't do modding when you are too tired to do it properly.

**Comment by simon-82** [comment]
syringe recipe fixed in 1.15

**Comment by BorealisPhoenix** [comment]
Nah your fine keep up the good work. I wouldn't play this game without your pack.

**Comment by simon-82** [comment]
Thanks, glad you enjoy it :smile:
