### ISSUE TITLE
switch to nutrition

### ISSUE THREAD

**Issue by simon-82** [simon-82/ModVarietyPack#29]
Concepts and ideas for switching to nutrition based meals. 
Targets are Thingdefs `SimpleSalad`, `Jerky`, `SimpleMeal`, `FineMeal` and `LavishMeal` for now. 

Chains: Plant - RawFood - Meal / AnimalCorpse - RawMeat - Meal / FishCorpse - RawFish - Meal

Focus is the Plant - RawFood - Meal chain. 

**Current Plant scaling for reference:** 

```
Base        (GrowTime 6.2, Yield 8)   Potato
Tier I      (GrowTime 5.7, Yield 10)  Eggplant
Tier II     (GrowTime 5.2, Yield 12)  Mushroom
Tier III    (GrowTime 4.7, Yield 14)  Carrots

Base        (GrowTime 4.9, Yield 6)   Rice
Tier I      (GrowTime 4.4, Yield 8)   Squash
Tier II     (GrowTime 3.9, Yield 10)  Onion
Tier III    (GrowTime 3.4, Yield 12)  Lettuce

Base        (GrowTime 13.7, Yield 22) Corn
Tier I      (GrowTime 13.2, Yield 24) Pumpkin
Tier II     (GrowTime 12.7, Yield 26) Bean
Tier III    (GrowTime 12.2, Yield 28) Tomato


Fruit Scaling: (!Agave can't be grown!)

Base        (GrowTime 5.3, Yield 6)     Strawberry
Tier I      (GrowTime 5.1, Yield 7)     Blueberry
Tier II     (GrowTime 4.9, Yield 8)     Cloudberry, Pineapple
Tier III    (GrowTime 4.7, Yield 9)     Gooseberry, Watermelon
Tier IV     (GrowTime 15-18, Yield 50)  FruitTrees (Not destroyed when harvested)

Growing:

Base        cultivated soil    (Plants: fertilityMin 1.0, fertilityFactorGrowthRate 0.05)
Tier I      fertilized soil    (Plants: fertilityMin 1.5, fertilityFactorGrowthRate 0.03)
Tier II     watered soil       (Plants: fertilityMin 2.0, fertilityFactorGrowthRate 0.02)
Tier III    enriched soil      (Plants: fertilityMin 2.5, fertilityFactorGrowthRate 0.01)
Tier IV     = Tier III
All Ressource Plants = Base
```

Current recipe `SimpleMeal`:
1 `SimpleMeal`  = 10 `RawFood` 

Example for Base Plant Potato 1 Square:
8 `RawFood` in 6.2 days =  1.3 `RawFood` / day = 0.13 `SimpleMeal` / day

Example for Tier III Plant Carrots 1 Square:
14 `RawFood` in 4.7 days = 3.0 `RawFood` / day = 0.3 `SimpleMeal` / day

**Changes for nutrition:**
The following is taken from unmodified Core:

Recipe `SimpleMeal`: _needs: IngredientValueGetter_Nutrition_
1 `SimpleMeal`  = 0.5 `Nutrition`

Example for Plant Potato (0.05 Nutrition) 1 Square:
8 `RawFood` in 6.2 days = 1.3 `RawFood` / day = 0.065 `Nutrition` / day =  0.13 `SimpleMeal` / day

_Side note: RawMeat also has 0.05 nutrition (so also 10 per meal)_
_All RawFood in vanilla has 0.05 nutrition_

New scaling for nutrition (WORK IN PROGRESS):

```
Base        (GrowTime 6.2, Yield 8, Nutrition 0.05 )   Potato *keep as base*
Tier I      (GrowTime 5.7, Yield 10, Nutrition 0.06)  Eggplant
Tier II     (GrowTime 5.2, Yield 12, Nutrition 0.07)  Mushroom
Tier III    (GrowTime 4.7, Yield 14, Nutrition 0.1)  Carrots

Base        (GrowTime 4.9, Yield 6, Nutrition 0.05)   Rice *keep as base*
Tier I      (GrowTime 4.4, Yield 8, Nutrition )   Squash
Tier II     (GrowTime 3.9, Yield 10, Nutrition )  Onion
Tier III    (GrowTime 3.4, Yield 12, Nutrition )  Lettuce

Base        (GrowTime 13.7, Yield 22, Nutrition 0.05) Corn *keep as base*
Tier I      (GrowTime 13.2, Yield 24, Nutrition ) Pumpkin
Tier II     (GrowTime 12.7, Yield 26, Nutrition ) Bean
Tier III    (GrowTime 12.2, Yield 28, Nutrition ) Tomato
```

---> Example for Tier III Plant Carrots 1 Square (better nutrition):
14 `RawFood` in 4.7 days = 3.0 `RawFood` / day = 0.3 `Nutrition` / day =  0.6 `SimpleMeal` / day

**Comment by Tapkevich** [comment]
Here is my thoughts. 
1. First we have to decide what balance between realism\enterteiment we wont to achive. How much we want our players to feel all harsh part of survival in Rimworld. In my opinion things SK doing is not something people want. I think we need to be somewhere between vanila with its simple gameplay and small depth and hardcore pack with overwhelming complexity. 
2. We need to decide if we want to keep current core food mechanic. Now it looks like this :
![rimworld_food](https://cloud.githubusercontent.com/assets/15946372/11312525/a8c2fea0-8fe7-11e5-9612-1af2d75527a1.png) and i think its pretty native system that still allow to build deep  around it. Create something different probably will be just waste of time. 
3. I'm not rly in modding rimworld, but as i see we cant create recipe for a meal, that will change characteristics of final product by changing type of raw food we use ?  Creating apparel, weapons,  structers work that way, but im not rly sure its possible to make food that way. If it is, well, it will make possible to create insanely deep system. 

That's kinda it for now, after geting answers on this questions i can start create numbers and math for food system.

**Comment by simon-82** [comment]
I am trying to switch from 10 = 1 to nutrition based meals. That's the point here. Everything else, make a new issue please. The system in the modpack is based on 10 raw vegetables / meat = 1 simple meal. 
I will update my first comment with the system I am working on.
1. True. 
2. Your graphic is not really accurate tbh. It's more like raw food -> meals, not a split between raw food and meals. 
   Anyway, as said above, this is about switching to nutrition. Nothing more, nothing less. Lots of complexity / depth can be added that way. Some examples: 
   Tier I raw food gets higher nutrition than base raw food -> less tier I food per meal -> more meals per plant -> less farming/harvesting/work per meal. 
   Tier II raw food gets higher nutrition than tier I raw food ... you see where this is going. 
   In addition to that, the incentive to upgrade to better soil (fertilized, watered...) gets higher. Making it worth to upgrade the soil. 
   I am also experimenting with another way to limit the the better plants to be grown only on better soil while still maintaining the fertility bonuses. Example: base plants grow on cultivated soil with 100%, fertilized soil with 110%. While still have tier I plants grow on 100% on fertilized soil. It's not easy, but I think I have an idea to make it work. 
3. A meal is a meal. It is not made out of stuff, so it will stay the same. But that's ok. We have plenty of different meals in the modpack already and more will come from "gourmet garden". And we have so many plants to make different meals from. It would e boring to have only one "generic meal" with different stats. Instead we can have wheat -> bread and raw meat -> grilled meat and bread + grilled meat = burger. You see what I mean? More variety is nice. 
   And this one more thing about your graphic. A burger can be a meal which is both, nutritious AND gives joy. It's hard to make because of the increadients, but has great benefits when eaten by colonists. 
   Actually, you can make a meal do 3 things: Fix x% hunger, give x% joy and give direct stat bonuses (for example x% blood filtration for x hours)
