### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Zorro12322** [simon-82/ModVarietyPack#3]
This mod looks like so much fun but i cant fiqure it out if you can send a video or more in depth explanation
Create a shortcut and add -savedatafolder SaveData to the end of the command line used to launch the game.
Where is this and so but please it looks like sooo much fun

**Comment by simon-82** [comment]
Go to the folder you installed the game in. 
Right click the rimworld.exe file.
Select "create shortcut".
Now right click the new shortcut you created and select "properties".
In this window, the first line you can edit reads something like "C:/RimWorld/RimWorld914Win.exe"
It may be different, depending on where you installed the game.
Change this to be like this "C:/RimWorld/RimWorld914Win.exe -savedatafolder SaveData"
The part before " -savedatafolder SaveData" can be different for you!

I added this to the readme. If you need more help, just ask :)

**Comment by simon-82** [comment]
added this to the readme file.

**Comment by Zorro12322** [comment]
um under start in or target??

**Comment by Zorro12322** [comment]
its not working i did it in target and i went in mods and accepted where there was a check and when i create a world then play it i dont have any mods it is like vannila and i open it in shortcut if you can make a video

**Comment by simon-82** [comment]
It is in the target field. 
I am sorry, I don't quite understand you. It's really not that hard. 
You "went in mods and accepted where there was a check"? What? Where? in the game? You don't have to do that. Did you copy the SavaData folder and the Mods folder?

**Comment by chasra** [comment]
i did this and then what? all the mods but the core are inactive.. i hit to activate them and it wont load the game. it disables all the mods saying there is out of date or incompatible mods.. what do i do now?

**Comment by simon-82** [comment]
You don't have to activate the mods yourself. They must be loaded in a specific order. 
In the zip file are 2 folders. The one called _SaveData_ has a file called _modconfig_ in it. That one tells the game the mods it has to load. 
If you followed the instructions, there should be also a SaveData folder in your game after you have launched it the first time with the shortcut. After that, if you copy my SaveData folder in there, the old file should get replaced with my new modsconfig. 
You are always launching the game with the shortcut, right?

**Comment by simon-82** [comment]
No more questions posted. Closed for now.
