### ISSUE TITLE
Broken Textures

### ISSUE THREAD

**Issue by MechanoidHivemind** [simon-82/ModVarietyPack#38]
I followed everything down to a T, What am i missing here    (http://puu.sh/lybTm/18e58383a9.jpg)

**Comment by simon-82** [comment]
Don't know. Just started the game to check. 
It's all fine here. Try a clean install.

![screen](https://cloud.githubusercontent.com/assets/14851041/11403832/46f84e76-939f-11e5-8c42-8f2c8fd85a77.jpg)
