### ISSUE TITLE
Weird Bug

### ISSUE THREAD

**Issue by Videoboy** [simon-82/ModVarietyPack#4]
I loaded Rimworld with this modpack as usual, loaded my save, and there was nothing but the toolbar and speed control keys. I deleted this save, and made a new colony on the same world. Now, it wont let me use the ESC key and I am unable to click. Help!

**Comment by simon-82** [comment]
Seems weird indeed. 
Please follow the readme and do a clean install without other mods. 
If it's still not working provide an output log please.
