### ISSUE TITLE
Growing Zone Dilineator Location?

### ISSUE THREAD

**Issue by eeke1** [simon-82/ModVarietyPack#43]
I'd like to also use the mod: Seeds Please with this one.

It works fine, but the caviat is the growing zones are now default anywhere.

This isn't the biggest problem, but it bugs me. I've looked through the defs for both that mod and this one trying to find how the Growing Zone was restricted in this one or set back to default in that one, but no luck.

Could you please point me in the right direction?

**Comment by simon-82** [comment]
Take a look at 
Terrain_Natural.xml and Plants_Cultivated.xml
