### ISSUE TITLE
Few observations

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#45]
These are from play 1.16

Power research says it increases battery efficiency, but the batteries stay at 50%.

Tool cabinet and multi analyzer unlocks twice.

Water bucket only being made from wood planks does not work in the desert. need options. 10 planks per wood bucket is expensive since the bucket is destroyed when used. I know you can't return the bucket in recipes, since that makes the "do until" not work. maybe reduce the resource needed to 1 or 2? for the bucket since those resources are lost when the bucket is used. 

Might want to adjust the egg nutrition value, it is .25, therefore only 2 eggs are needed for a simple meal. Base game value.

Would like to be able to use the refrigerated serving table to store medical also, or create a refrigerated medical cabinet. Would also like to have a storage like the weapons rack for food/drink that does not need refrigeration... nice to put drinks close to the tables.

Improvements made to the soil requirements help. 

Personally the canning stove needs to unlock sooner than it does... Canning should come before refrigeration. Maybe unlock at ag II before cooking I.

**Comment by simon-82** [comment]
Nice findings :+1: 

Batteries: Can fix. Overlooked by me.

ToolCabinet: They should both unlock with crafting I, when else do they unlock? 

WaterBucket: In the desert you can get wood from cactus, right? Maybe 10 woodplank is too much. Maybe do woodlog or bamboo, and 5 per bucket? 1 or 2 is maybe not enough? Not sure. 

Eggs: Yes .25 is base game value. and meal .5 is also base game value. But chickens need lot of hay and don't give that many eggs... What do you suggest? 1 egg = .05 nutrition like plants?

Serving table: Good idea! Just edit the storage settings you mean? Need a new texture for a refrigerated medical cabinet maybe. 
I like the idea of having drinks near the tables. Something like a bar in the living room to serve the guests some drinks. Maybe with a small lamp on top? Hehe, looks like a job for you? EndTable version 2? Now with drinks? :smile: 

Canning Stove: Can do. Ag II sounds reasonable.

**Comment by TLHeart** [comment]
Yes tool cabinet unlocks at crafting I, but crafting II descriptions say, also unlocks tool cabinet and multi analyzer.

Yes wood comes from cactus in limited quantities... 10 planks per bucket for soil, and 10 planks per bucket for alcohol uses up the wood supply very quickly. Now if the bucket was reusable, then I would have no problem with the cost, but I have found no way to have a recipe have two production items,  due to the base game code, and still use the "do until" bill.  An example, Need to water 30 cells of soil, that is 300 planks, or 200 logs. Now I also want to brew beer, that is 10 planks per 5 bottles of beer. One quickly runs out of wood. That is why I said 1 or 2, but not sure.

Chickens give 1 egg every 2 days. And they eat native grass. An egg being .25 is huge. I have played around with .15. 2 eggs and 4 base veg/meat equals a meal then. Also played with .08, so that 3 eggs and 6 veg/meat make a meal, or 2 eggs and 7 veg meat make a meal. 

For my personal use, I have the medical cabinet like you have, and a refrigerated version of the medical cabinet. That way I can build a counter along the wall for supplies. I can keep herbal meds in the prison for quick use, and not be concerned about spoilage. 

here is a link to a screen shot of a dinning room with refrigerated foods and drinks. I was using the texture from soda garden. The one with the blue edge are refrigerated.

https://scontent-sea1-1.xx.fbcdn.net/hphotos-xpf1/v/l/t1.0-9/1502567_1039479086083451_6827839632198745584_n.jpg?oh=1eaf5e39fe85217af823b9199a224c44&oe=56DC3A6E

**Comment by simon-82** [comment]
nice screenshot :+1: 
I will make the bucket of water cost 3 woodlog or 3 bamboo. 
Eggs I am not sure. The vanilla game has it on .25. Not sure if I want to mess with the base game values. I mean it still requires a lot of effort to keep chickens, especially over winter they need heat and food or they die. I feel it should be possible to make lots of meals from eggs. If you want to run your colony only on chickens, it should be possible. More choice for the players.

**Comment by TLHeart** [comment]
That is fine on the eggs, I understand.

Might also want to check the nutrition on the cave world mushrooms. one is 8% while another is 12 or 15%. Don't know if you set those.

**Comment by simon-82** [comment]
They are set as default by the mod. 
But hey, you cant plant those yourself and only find them in caves. So I guess these are ok maybe.
It's not like you get 1000s of those easy
