### ISSUE TITLE
Request: adding wave survival

### ISSUE THREAD

**Issue by Paragonid** [simon-82/ModVarietyPack#46]
There's a wave survival storyteller, I would love to see in the modpack.
https://ludeon.com/forums/index.php?topic=10976.0
http://www.nexusmods.com/rimworld/mods/75/?

It's not updated to the A12 yet and no source available. But I hope one day it will be.

**Comment by simon-82** [comment]
Hm, nice idea but no source available.

**Comment by Paragonid** [comment]
It's updated to A12 by someone (not author)
https://ludeon.com/forums/index.php?action=dlattach;topic=10976.0;attach=10785

**Comment by simon-82** [comment]
Nice, thanks for the link. :+1:
