### ISSUE TITLE
Conduit walls

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#47]
Conduit walls are throwing errors when loading a saved game.

Misaligned load ID request. Requests didn't match between the LoadingVars and ResolvingCrossRefs stage. Id PowerConduit602758 was entered as a Verse.Thing but is being read as a Verse.Pawn.

(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

Exception getting object with load id PowerConduit602758 of type Verse.Pawn. What we loaded was PowerConduit602758. Exception:
System.InvalidCastException: Cannot cast from source type to destination type.

  at (wrapper managed-to-native) object:__icall_wrapper_mono_object_castclass (object,intptr)

  at Verse.LoadedObjectDirectory.ObjectWithLoadID[Pawn](System.String loadID) [0x00000] in <filename unknown>:0 

(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

Also can not place any of the vents, or heater coolers that attach to walls on conduit walls.

**Comment by simon-82** [comment]
It says:
PowerConduit602758 was entered as a Verse.Thing but is being read as a Verse.Pawn.

So it got saved as a thing (a wall is a thing) and loaded as a pawn (a colonist / animal)
I guess the save got corrupted. I just tried saving with a conduitwall and could load without errors. 
Can you reproduce the error with a new save?

As for not being able to place things on top of them, I think I know where the problem is. 
I will investigate.

**Comment by simon-82** [comment]
fixed the heaters and stuff can now be placed on conduit walls - same error was for lighted walls btw. :+1:

**Comment by simon-82** [comment]
your save / load error popped up for someone else on the forums. 
Seems to be a real problem, not something random on your side unfortunately. 
Can you upload your savegame and world with the error? 
I still can't reproduce it myself. Not sure where the problem is right now :disappointed:

**Comment by TLHeart** [comment]
sure, still playing it with the error. The world file is part of the save file.  But unfortunate, git does not allow that type of file, only text and picture files. I will upload a 7zip to the forum for you.

Maybe this line is the real problem.

Misaligned load ID request. Requests didn't match between the LoadingVars and ResolvingCrossRefs stage. Id null was entered as a RimWorld.Tale but is being read as a Verse.Thing.

**Comment by simon-82** [comment]
Seems you are right. 
What I found so far:
- The things that throw the error are not only conduitwalls but also powerconduits, its actually different errors on subsequential loads of your save. 
- Every PowerConduit/ConduitWall with an error has a powered furniture connected to it that has Art (Rimworld.Tale is art). (Found a EndTable with Art (exc. quality) and a cooled serving table with art) The conduits they are connected to give both this error  

Big question still is, why it is doing that though.

**Comment by simon-82** [comment]
The error with Rimworld.Tale is caused by this: 
Here a chair with art (thats how it should be I suppose):

```
<taleRef>
<seed>3463426326</seed>
<tale>20</tale>
</taleRef>
```

Here an EndTable with art connected to a powerconduit that throws the error:

```
<taleRef>
<seed>235252525</seed>
<tale>null</tale>
</taleRef>
```

**Comment by simon-82** [comment]
Confirmed: 
- Deconstructed all of the Art Furniture connected to the various PowerConduits giving the error.
- Saved again.
- Loaded. No more errors.

-> Source of the error needs to be found in furniture defs I guess.
In your save, that was the one cooled serving table and 3 EndTables  (all exc. with art)

1st guess: Furniture which needs power can't have art. 
So maybe changing the base of these to FurnitureBase instead of HighQualityFurnitureBase could solve it

One more thing:
The user on the forum with the same error posted some pictures.
He has one of these errors in the log. 
As far as I can see, there is exactly one cooled serving table on the pictures. Can't see any EndTables.

**Comment by TLHeart** [comment]
That appears to be the easy fix.

**Comment by simon-82** [comment]
It can only be the real cause if there is no powered furniture in the vanilla game though. 
But I can't think of any right now.

**Comment by TLHeart** [comment]
the only powered furniture in the vanilla game is the standing lamp. It is defined as a building, and does not have art but does have quality

**Comment by simon-82** [comment]
I wonder why you said "That appears to be the easy fix"? 
My guess is it just not implemented in the base game to have furniture that requires power and has art.

It would explain why the savegames get all messed up and the game can't read it, right? 
I mean a tag (here "Tale") gets saved to something which shouldn't have this tag -> load order gets messed up

**Comment by TLHeart** [comment]
Tested in vanilla, added art to the lamps, and it works....no errors. Has to do with the order of the comps. Art MUST be the last comp for it to work correctly. Since the power comps are added into the definition of the endtable, the power comes after the art, and the error occurs.

Here is the save file with art comp before power comps. It has the error.

```
        <thing Class="Building">
            <def>StandingLamp</def>
            <id>StandingLamp53957</id>
            <pos>(148, 0, 132)</pos>
            <health>50</health>
            <faction>Colony1561057835</faction>
            <authorName>Vasily Powell</authorName>
            <title>Hadley's Intimacy</title>
            <taleRef>
                <seed>1657361418</seed>
                <tale>null</tale>
            </taleRef>
            <parentThing>SolarGenerator53738</parentThing>
            <quality>Excellent</quality>
            <glowOn>True</glowOn>
        </thing>
```

And here is the save with art as the last comp;

```
        <thing Class="Building">
            <def>StandingLamp</def>
            <id>StandingLamp59726</id>
            <pos>(116, 0, 134)</pos>
            <health>50</health>
            <faction>Colony1669907631</faction>
            <parentThing>SolarGenerator54785</parentThing>
            <quality>Excellent</quality>
            <authorName>Paul Richard</authorName>
            <title>Loyalty</title>
            <taleRef>
                <seed>1993629821</seed>
                <tale>1</tale>
            </taleRef>
            <glowOn>True</glowOn>
        </thing>
```

**Comment by simon-82** [comment]
wow.... 
So by adding art as the last comp in the thingdef you get no error, if I understand you correctly. 
That is crazy that the order of the comps matter. 

But the error you get with the vanilla lamps WITH art NOT loaded last is the same we have from the beginning, right?

If so, we have solved the issue by switching around the comps in the thingdef. 
Phew... well ok then.

**Comment by simon-82** [comment]
wait, no no... 
The base gets loaded before any actual thingdef. 
So in case of a bed for example, you have a comp "CompAffectedByFacilities" - "vitals monitor" loaded after the art comp in the base. 

Now a bed doesn't need power. But a comp gets loaded after art and it works.

So more specifically, the art comp must be after power.

**Comment by TLHeart** [comment]
Really the order of the comp should not matter, but with art it appears it does. Power and art have some conflicts that tynan would have never seen since the base game does not have art on powered furniture.

**Comment by simon-82** [comment]
Well, go give him a link to this issue thread then :+1: 

I'll switch those comps around for the next release of the modpack to solve the issue. 
Thanks for helping, good job :smile:

**Comment by TLHeart** [comment]
Your welcome, as it has been bugging me.

**Comment by Karel-Kroeze** [comment]
I think this is probably related to an old (and known) bug with scribing - references need to come after values. https://ludeon.com/forums/index.php?topic=14485.msg150887#msg150887.

**Comment by simon-82** [comment]
Interesting. Thanks for sharing the link! 

Switched order of comps now :+1:
