### ISSUE TITLE
Tofu

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#48]
Tofu is a meat substitute, but because you have it classified as a meal, it is not being used in the meal recipes. Either needs to be classified as raw meat, or add tofu to the meal recipes.

**Comment by simon-82** [comment]
Hm, I understand. Classified as raw meat? Hm, need to think what the consequences are and if that breaks anything. I think it could work as raw meat.

Funny that you mention meat right now. I was working on adding some meals. Just made a Burger, Cheese Burger and a Deluxe Burger :smile:

**Comment by TLHeart** [comment]
Classified as raw meat is the easy solution, that way it will work in any recipe that requires meat... as a meal you will have to enter it into the actual individual recipes.

**Comment by simon-82** [comment]
Yes I was trying to do that right now. Not easy with the nutriton values though. 
Need to have more than raw beans. But not too much to make them comparable to meat. All meat has the standard .05 nut. But raw beans already have .07. 
I will do it like this I think:
1 square of beans yields 24
So I make 1 tofu = 24 beans
And 1 tofu = 0.125 nutrition
So 1 tofu = 2.5 meat
Hmmm, is that ok?
For a fine meal you would need .025 nutriton 
So 2 tofu or 5 meat

**Comment by TLHeart** [comment]
Sounds good, on paper.. 2 to 5 is a fair deal for the work required for the tofu.

On the burger recipes, how about adding them to the grill, which makes the grill a usable item later in the game.

**Comment by simon-82** [comment]
Oh nice idea with the grill. Will do that!
I just made the textures for the burgers and updated other textures I didn't like so much.

**Comment by TLHeart** [comment]
One other thought, to help with recipe clutter, make the canning stove be the prep stove, where items used in meals are prepared. Like cheese, tofu, soy milk, chocolate, and of course canning.

And with the canning stove I would like to see 3 canning recipes... one that creates a simple meal, 0.5 nutrition, needed to make, just like the meals. This is the one now on the canning stove.

 Then 2 other recipes where we can the ingredients to make an ingredient which prolongs shelf life, 0.25 nutrition to make the canned ingredients. One for vegetables, and one for meats, both after canning still have the 0.25 nutrition. For balance have the recipe require 0.5 input, 1 steel  with the output 2 canned ingredients.

This gives another way to preserve food. And with the canning stove at agII makes the rush to refrigeration an option, that can be put off, while security is researched.

**Comment by simon-82** [comment]
You need to write that again. I did not quite understand.
So the idea is cool, making the rush to refrigeration an option.
But how do the other 2 recipes work? Sorry, didn't get it :confused:  

As for the canning table, when you look at the texture, its only for canning really. And it makes sense, you would need some machine to do that.

There is the butcher table though. It is renamed in the modpack as "food prep table" 
Maybe add stuff to that would make more sense maybe?

**Comment by TLHeart** [comment]
Ideas, at time hard to explain. :)

The two new canned items are not meals like a simple meal.

Take 5 potatoes, which equals .25 nutrition. Can those potatoes, won't spoil. The canned potatoes still have .25 nutrition, and can be used in meal recipes, just as fresh vegetable may be used.

Take 5 meat, which equal .25 nutrition. Can the meat, won't spoil. Still has .25 nutrition, as a canned meat. The canned meat is used in meal recipes just like raw meat.

Present canned meal requires 0.5 nutrition and 1 steel, which provides 1 canned meal.

I propose these recipes.
Canned Veg/fruit
Requires 0.5 nutrition, 1 steel, provides 2 canned veg/fruit of 0.25 nutrition.
Is used in meal recipes in place of raw veg/fruit.
Makes meal CannedVeg
Category of PlantFoodRaw would be simple implementation.
Or have to change all recipes you want it used in.

Canned Meat
Requires 0.5 nutrition, 1 steel, provides 2 canned meat of 0.25 nutrition.
Is used in meal recipes in place of raw meat.
Makes meal CannedMeat.
Category of MeatRaw would be simple implementation.

With the low nutritional value, the colonist will not eat the canned veg or canned meat unless desperate.

**Comment by simon-82** [comment]
Nice idea. I understand now what your intention was.
But where is the true benefit? Why not just make canned meals straight away and store these?
I mean you will eventually use your canned rawfood to make meals anyway. 
So all your recipes do is adding another step, right?
Or am I not seeing something obvious here?

**Comment by TLHeart** [comment]
Currently, canned meals can not be used in recipes. It may just be an idea, that really has no benefit. Thinking out loud. I was looking for a way to store foods without refrigeration for the long term, that could be used in meal creation. Still trying to flush out the details, and does it provide any benefit.

Or does it just add another step of complications, like SK does?  which by the way I hate.

**Comment by simon-82** [comment]
Hm, ok I see. Storing food for later use. But my point still stands, If you put in the work of canning food, why not make canned meals directly?

**Comment by TLHeart** [comment]
Your point is taken.
