### ISSUE TITLE
pineapples

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#49]
would be nice to know pineapples are planted like trees, and need an open space between plants... lots of wasted work creating the watered soil to have over half the soil not being used.

I actually don't understand the choice to make pineapples require the extra spacing like trees.

**Comment by simon-82** [comment]
I never thought about it actually. Good point. They are different in that they act like trees but get destroyed when harvested, right? 
So being different is good. But maybe they need more benefit for the space they need? 
Suggestions? 
Maybe yield more or yes, maybe higher nutrition would be good, because pineapples are huge fruits compared to the others, so you could make more food from one pineapple than from a berry for example.

**Comment by TLHeart** [comment]
Yes pineapple gets destroyed when harvested. A pineapple is no larger than a cotton bush, or a blueberry bush.  If you are going with the pineapple produces more think about this.

XXX      XXXXX
XPX      XPXPX
XXX      XXXXX

One pineapple needs 9 squares of space, 2 need 15 squares of space... going to need to really boost the output to make them worth growing.

Or consider this, that the leaves are also used to make cloth in the Philippines. Have the harvest also produce the raw leaves, that are turned into a cloth at the loom.

**Comment by simon-82** [comment]
Interesting idea and I didn't know that about the Philippines. 
Now the problem I see that it would add another ressource only used for making cloth. Just as with the worktables, I only add them when there is really no other way. To keep things neat and tidy, you know?
While I really think that is an interesting idea, I would rather boost the plant and / or the fruits themselves. 
Or do you think changing the spacing is better? I kinda like that they are different though.

**Comment by simon-82** [comment]
So cloudberry and pineapple are the same right now
(GrowTime 4.5, Yield 8, NutritionRaw .07)
Only pineapple has this activated:

```
<blockAdjacentSow>true</blockAdjacentSow>
```

What about just making pineapples like this:
(GrowTime 4.5, Yield 8, NutritionRaw .125)

**Comment by TLHeart** [comment]
That may work, just add to the description that the pineapples take additional space like trees to grow.

**Comment by simon-82** [comment]
New release has the fruits changed to that value. Will edit the description for the next release.
