### ISSUE TITLE
Seeds still in the storage options.

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#5]
Loaded the new version, great idea, but seeds category is still listed in the storage settings. can not open the sub menu. and it does have a red x, which can not be changed. Small problem.

Other question, why are you including the core file with your mod?

**Comment by simon-82** [comment]
Thanks for reporting!
Ah I missed deleting the ThingCategory of Seeds. It's an easy fix.
The Core folder is only there for changing some vanilla textures. Some won't override any other way. If you have an other solution for this, please let me know :) 
And you are a modder yourself, aren't you? If you wanna join the project or have something changed, you can fork the project on github and send me pull requests any time :)

**Comment by TLHeart** [comment]
I am a small modder, tweaker of the game... never attempt something like this. Most never leave my computer. Many are just small additions to other peoples mods, so I never share those except with the author of the mod. up to them if they want to incorporate my idea.

**Comment by simon-82** [comment]
Cool. I was just asking... If you want to contribute anything, feel free :)

**Comment by simon-82** [comment]
bug fixed
