### ISSUE TITLE
Coffee machine texture

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#51]
When I zoom out the coffee machine disappears. The texture size is wrong it is 64x66. Needs to be 64x64. easy fix with gimp to resize to 64x64.

**Comment by simon-82** [comment]
nice find. :+1:  will resize.

Oh btw, you are creating these issues, thanks for that, but can you also close them when you don't have anything more to say? 
I am sometimes not sure if I can close a issue from you because you are not replying to it any more.

**Comment by TLHeart** [comment]
I can do that. Burst of energy for me since I am between medical treatments.

**Comment by simon-82** [comment]
Oh, sorry to hear that! I hope you are doing fine and it is nothing too serious?
