### ISSUE TITLE
Severity of strong Alcohol

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#54]
Looks like you are using the old hediiffs from alcohol from vegetable garden. And that cause lots and lots of vomit. Makes brewing alcohol not worth it. 

Dismarr did adjust the values down slightly, so that one drink did not result in sickness.

He lowered the strong alcohol to .3 for the first drink, which is just below the sickness stage...2 strong drinks results in sickness.

**Comment by simon-82** [comment]
You mean 

```
<initialSeverity>0.3</initialSeverity>
```

for strong alcohol? 
I have also 

```
<initialSeverity>0.32</initialSeverity>
```

for medium alcohol. Maybe tune that down to 0.2 then also?

**Comment by TLHeart** [comment]
Exactly, and yes medium alcohol to .2. Sure glad you found what I was aiming for.

**Comment by simon-82** [comment]
Cool. Can you check on the powerconduit issue again? Maybe I found something
