### ISSUE TITLE
Silent Jaw not craftable

### ISSUE THREAD

**Issue by ghost** [simon-82/ModVarietyPack#58]
... Mods\ModVarietyPack\Defs\RecipeDefs\Recipes_BodyParts.xml

<RecipeDef ParentName="RecipeBionicProsthesis">

fixedIngredientFilter has Steel ore and Plaststeel Ore instead of AluBar and PlaststeelBar

sorry i tried to upload the fixed Recipes_BodyParts but Github didn't like that also copying the code into this text did not work.

**Comment by simon-82** [comment]
thanks for reporting :+1: 
will upload a fix now.

**Comment by simon-82** [comment]
fixed in 1.21
