### ISSUE TITLE
Stone Cutter work bills

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#6]
See you have set up individual bills for each stone type. Bu it does not work as expected. I have limestone, slate, and marble in my area, so I set up bills to do 250 limestone, then 250 slate, then 250 marble.... but that is not what happened... 

I ended up with 20 limestone, 330 slate, and 400 marble.

The stone tweaks mod works correctly, so I know it can be done.

**Comment by simon-82** [comment]
I'll have a look at that.

**Comment by simon-82** [comment]
Hm. So I tried this now. For me it works correctly.
So I set up 2 bills for 160 limestone, then 160 marble.
Once the bill gets to 160, it turns red and no more blocks of that type get made. 
I am not sure what happened for you. How can they make blocks if the bill is no longer active? So for your case, the bill for slate got over 250. Did your bill not turn red when reaching 250?

**Comment by TLHeart** [comment]
Okay, derp on my part, after going through the save files I found where it happened, and it was totally my fault with changing storage zones.

I would like to suggest though, that you keep the vanilla stone cutting recipe also, as I know some players prefer that method.
