### ISSUE TITLE
Terrarforming pumps don't work after reinstalling

### ISSUE THREAD

**Issue by ghost** [simon-82/ModVarietyPack#63]
Terrarforming pumps stop working after uninstalling/reinstalling. If constructed and not moved they work fine.

**Comment by simon-82** [comment]
Thanks for reporting, I'll look at it

**Comment by simon-82** [comment]
Just tried installing / uninstalling it a couple of times. Pump started working again after re-installing. 
Did it have enough power?
What were the exact steps you did with the pump to make it stop working?
The more you can tell me, the easier I can find the issue :+1:

**Comment by ghost** [comment]
I will try to reproduce the bug. Will take some time as i will not be back home for several days.

**Comment by simon-82** [comment]
can't fix this unfortunately. Feature will be removed. I'll make it cheaper to build since it can't be uninstalled anymore though :smile:

**Comment by simon-82** [comment]
fixed

**Comment by ghost** [comment]
very well. Started a new game at first i was able to move and use them again but midgame/endgame the pump-Moving broke down again. No idea why. (v. 1.2.1) does the terrarformer mechanoid event introduce an new terrain type that can not be terrarformed and the pumps break down? - i have no idea i am not a modder just speculating.

**Comment by simon-82** [comment]
sorry, by fixed I mean the pump can't be uninstalled now (1.22). :stuck_out_tongue: 
mechanoid terraformer is a mach base that lands on the map and prepares a mech invasion. Does not change terrain
