### ISSUE TITLE
Compatibility with Colony manager V2 (consider integrating)

### ISSUE THREAD

**Issue by Ristellise** [simon-82/ModVarietyPack#64]

**Comment by Ristellise** [comment]
using modpack with colony manager does not play well. NRE when debug is on. people do not listen to global work in colony manager.

**Comment by simon-82** [comment]
Good idea :+1: 
I never tried it. 
Fluffy has used it with the modpack before and said it would work fine though. 
He even has screenshots posted usind it with the modpack (first post of the colony manager thread)

**Comment by simon-82** [comment]
added
