### ISSUE TITLE
Missing Fissure generator for Ore Extractor

### ISSUE THREAD

**Issue by ghost** [simon-82/ModVarietyPack#65]
Hi! I'm unable to build Ore Extractor.
Error message popups: OnFissureReportString.
There's no Fissure generator anywhere in build menu.
Running last RIM + ModVariety v1.21.

**Comment by simon-82** [comment]
ok I check it. Fissure Gen should be under misc.
Needs research

**Comment by ghost** [comment]
I'm so terribly sorry. It's not missing :(
Please close.

**Comment by simon-82** [comment]
So what about the error message you have? 
Where did this pop up for you? 
No problem btw, thanks for reporting :smile: 
And thanks for playing with the modpack, I hope you are having fun? 
If you have any suggestions, wishes, whatever... don't hesitate to make an issue here :smile: 
And if you feel your issue has resolved, you can also close it yourself :+1:
