### ISSUE TITLE
Restriction Tab not updating

### ISSUE THREAD

**Issue by ghost** [simon-82/ModVarietyPack#67]
The Restiction Tab shows my Colonists as injured/crossed out after a reload. The save is from before they were shot. 
Restarting the game and loading the same Save fixes the problem.

**Comment by ghost** [comment]
- was unable to reproduce the bug after reloading the game. - before reloading the bug was reproduceable.
  When i clicked on the colonists in the restriction tab while the bug accured after reloading, it showed them at the location where they were (will be) incapacitated (to specify it showed the selection box) - same as when colonists go on a Mission and vanish at the edge of the map but can still be selected.

**Comment by simon-82** [comment]
any errors in the log?

**Comment by ghost** [comment]
no

**Comment by simon-82** [comment]
Hm, hard to know for me what has happened then and how to fix it. 
Are you using other mods beside the modpack? Did you do a clean install?

**Comment by ghost** [comment]
i did not encounter the bug again. Since it is not reproduceable --> close
