### ISSUE TITLE
Suggestion; Don't overload tables with recipes.

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#69]
Progress is good, and I like most of what you have done. Would still like to see the canning stove used for more than just canning. Having a one recipe workbench in the kitchen, when the prep table is now overwhelmed with recipes between butchering, and preparing foods. Would also like to see a bulk grind stone.

And when you reach 30 or more recipes on any worktable, the float menu cuts off the 30th recipe, and places the 31 recipe in the second column. 

This also applies to the medical operations float menu.

**Comment by simon-82** [comment]
Hm. Yes I agree, too many recipes on one table is a bad thing. 
The food prep table does have more than only butchering now, but not too much IMO. 
What does it have? 10? 15 max, right? 
But regarding the canning table, I still stand by my opinion that canning food needs its' own machine. And the table is only 2 squares anyway. 

The number of recipes in one column is mostly determined by the screen resolution. 30 per column is when running on 1080p? 

Yea, the most recipes are probably in the operations menu and on the tailors bench. The weapon tables will have a lot, too. 
Of course I try to keep the numbers down, which is a balancing act as I don't want too many tables also. 

If you find anything that is bothering you, let me know :smile: 
Well, anyhing but the canning table :stuck_out_tongue:  It will be only for canning :stuck_out_tongue_winking_eye:

**Comment by TLHeart** [comment]
in your release, canning stove will only be for canning, not in my games. :)

So you would rather loose recipes on the tailors bench, the weapons benches, than have more usable work benches? 

Only one colonist can work at a bench at a time. 15 recipes on table, causes bottle necks in production, and I end up build 2 or three copies of that table to alleviate the bottle necks. 

So why even have the canning stove, just put the recipe on the stove then, with your way of thinking... a single use workbench is useless.  better yet reduce the kitchen down to just ONE table with all the recipes. No Need to clutter the room with different stoves, ovens, prep tables, when it can all be accomplished at one table. You know to keep the number of table down. Does not matter that only one colonist can use a table at a time, or that a huge list of recipes is NOT a good user interface.... who wants to dig through long lists to create something, just pick what is near the top and forget it.

You are being inconsistent. The canning stove is the ONLY table in the mod pack that has ONE recipe. Goes totally against the keeping the number of table down argument.

Okay rant over.

**Comment by simon-82** [comment]
Thanks for the rant, always nice to hear some feedback :stuck_out_tongue: 
As always, I totally understand your arguments, let me answer:     

> So you would rather loose recipes on the tailors bench, the weapons benches, than have more usable work benches?

Loose recipes? I don't have any lost recipes on any bench, right? I am careful not to add too much so it does not happen.

> Only one colonist can work at a bench at a time. 15 recipes on table, causes bottle necks in production, and I end up build 2 or three copies of that table to alleviate the bottle necks.

That is a good point. It depends on the size of the colony though. A small colony would not need more than one of each. And if you run a big colony, sure build more than one, Seems right to me. More colonists = more tables. 

> So why even have the canning stove, just put the recipe on the stove then, with your way of thinking... a single use workbench is useless. better yet reduce the kitchen down to just ONE table with all the recipes. No Need to clutter the room with different stoves, ovens, prep tables, when it can all be accomplished at one table. You know to keep the number of table down. Does not matter that only one colonist can use a table at a time, or that a huge list of recipes is NOT a good user interface.... who wants to dig through long lists to create something, just pick what is near the top and forget it.

As I said, it is a balancing act. And again, canning food needs a machine to do that. That's just the way it is. You need to press a can from steelbars and seal the food in it. That seems difficult on a cook stove, right?  
For the food-prep table: I took some recipes off the other kitchen benches and put them on there because it had the least recipes of all the tables. Now they all have an almost equal amount of recipes. That makes the food prep table more useful and balances the number of recipes accross the tables.  
Take the tailors bench for example (it has the most recipes = very long list). I was asking myself: Would it be better to have this long list or have a Pants-Table, a Hat-Table, a Shirts-Table and a Jacket-Table? So I went for the long list. I made that decision and I still think it was the right choice.

**Comment by TLHeart** [comment]
glad you took the rant for what it was. 

Canning stove takes a press, for the cans. Cheese also takes a press, to force out liquids. Tofu also needs a press to force out liquids. Makes sense to have items that need a press to be on the same table. 

Tailors table, Basic tailors table, for all the vanilla clothing. Norbal table for the norbal clothing, Federation table for the federation clothing. That way recipes are all accessible due to the way the float menus are generated, and the last item in column one is not cut off.

**Comment by simon-82** [comment]
Hm... You are starting to convince me with your canning stove... damn you! Stop that! :stuck_out_tongue:  
Well, I guess I could live with a compromise here. But to make this work in my brain, I need to make a new texture for the table (to make it look more like a press) and rename it. Maybe Pressing Table? Hm, that sound odd though... 
Need to think about it... 
Norbal clothes can't be crafted. Fed neither. But you would split tailoring up? Hm, I could do that. There are really a lot of recipes on that table. But needs again a new texture and new naming of the tables. Need to take a look at all the clothing and come up with a good grouping that makes sense. With the amount of craftable clothing I have now, 2 tables should be enough, I think.

**Comment by TLHeart** [comment]
Just so you are aware, all work benches are limited to 10 working bills... once you que up the tenth bill, the add bills button disappears.  

This becomes a real problem on the butcher/prep table, with 6 butcher recipes, witch are all needed if one is fishing. That only leaves 4 slots for the other needed items, flour, sugar, fuel, cheese, soy milk, tofu.

**Comment by simon-82** [comment]
@TLHeart Making progress with the tables and recipes :smile: 
I did a Hatter's workbench (cause there are a lot of hats, splitting these off makes sense)
![tablehats](https://cloud.githubusercontent.com/assets/14851041/12069173/a11f69b2-b022-11e5-80e3-acd4cd8fb7cf.png)

And I did a "Pressing Table" which will replace the canning table. But I don't know what name to give to give it :cry: It will have the canning food recipe, pressing tofu, cheese and soy milk and pressing fuel, I think? Maybe? What do you think? And do you have an idea for a name?
![tablepress](https://cloud.githubusercontent.com/assets/14851041/12069181/0c6c7494-b023-11e5-8343-63f68cb26256.png)

**Comment by TLHeart** [comment]
Yea there are a lot of hats... makes sense.
The graphic for the "canning stove" looks good.
A pressure stove... it takes a pressure cooker to can foods, and a pressure press to create the others. 

don't know if I like that name either. 

or maybe a pressure cooker?

**Comment by simon-82** [comment]
called it just "Food Press" for now. 
It has recipes for tofu, cheese, fuel, canning, soy milk and fruit drink
So only flour and sugar are left on food prep table + butchering
Seems ok, right? What do you think?
