### ISSUE TITLE
Walls

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#71]
Vanilla walls cost 5 material to build. Walls in variety cost 5 material to build.

Conduit and lighted walls cost 6 material to build, plus the steel, and plus the steel and glass.

The 6 material is a holdover from alpha 10, and the copy paste from UOM.

Just a small inconsistency that drives me batty.

**Comment by TLHeart** [comment]
Also noticed that the conduit wall and the lighted wall also have much lower hit points than the generic wall. 

Conduit wall is set to 225 max hit points,
Lighted wall is set to 300 max hit points,
generic wall is set to 350 max hit points.

**Comment by simon-82** [comment]
Good points. The conduit walls came from the SC mod though, not UOM.  
Will adjust the values. Or you could just send me a pull request for small things like this, you know? 
Anyway thanks for reporting :+1:

**Comment by simon-82** [comment]
adjusted values.
