### ISSUE TITLE
Blueberry pie

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#73]
Now this is a strange one, that I can not figure out.

Colonist take 5 slices of pie from stack, goes to table, eats one slice, leaves 4 setting on table.

Any ideas what is causing this strange behavior?

**Comment by Owai-Seek** [comment]
My guess would be the nutritional level of the food but I'm not completely sure, I haven't gotten around to using anything other than meals for my colony.

**Comment by TLHeart** [comment]
Not the nutrition level, as other foods/sweets have the same level, and they take one.

**Comment by simon-82** [comment]
Maybe the pie looked so delicious, he couldn't resist but take five of them? Then while eating the pie he realised that his eyes were bigger than his stomach. Happens all the time to me. :stuck_out_tongue:  
Seriously though, no clue why that is. Have you looked at the def for the pie? Anything different from other sweets there?

**Comment by TLHeart** [comment]
Could be, eyes too big.

Nothing I can find in the blueberry pie def is different from the others.

**Comment by simon-82** [comment]
added to all sweets now: 

```
<maxNumToIngestAtOnce>1</maxNumToIngestAtOnce>
```

hopefully fixes this.
