### ISSUE TITLE
Well

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#74]
Please make the well rotate, so that I can adjust the interaction spot to fit where I need it.

**Comment by Ristellise** [comment]
@TLHeart a more fitting name would be : rotatable wells.

**Comment by simon-82** [comment]
Need to make more textures for the well then. Good suggestion :+1:

**Comment by Karel-Kroeze** [comment]
the well is round, why would you need more textures? just copy paste... :P

**Comment by simon-82** [comment]
It has perspective to it and looks odd when turned around. Should have made it top-down in the first place :cry:

**Comment by Karel-Kroeze** [comment]
so don't turn it around? the viewer pespective doesn't change, nor does the roundness of the well. It would look the same from any angle. You could literally copy paste the main image to front back and side and it would work just fine?

**Comment by simon-82** [comment]
Yea good point there Fluffy! I will just do that then! Thanks for reminding me of that workaround :+1:

**Comment by simon-82** [comment]
done
