### ISSUE TITLE
Bug / Suggestion: Fix Sieges spawning with only Melee units.

### ISSUE THREAD

**Issue by Owai-Seek** [simon-82/ModVarietyPack#76]
I've had a few Siege's spawn with melee units only (wearing shields), this made them ridiculously easy to defeat and made the threat almost non-existent.

**Comment by simon-82** [comment]
I will take a look at that. Thanks for reporting the issue :+1:

**Comment by simon-82** [comment]
Looking at the files I found the only raiders that can start sieges are Outlanders and Pirates. 
I never had this happen to me. Which faction did this in your game? 
Did they actually siege? Did they build an artillery + sandbags? 
If they did, the raid is actually working normally. 
The weapons they have equipped is random. I can't change that 

Do you have a save game of this with the bugged raiders on the map?

**Comment by simon-82** [comment]
Nevermind, I think I found the issue :smile: 
Hopefully fixed now.

**Comment by Owai-Seek** [comment]
Even though you think you've fixed it I feel obligated to answer anyway (seems a bit rude to leave them unanswered.)

I'm Fairly Certain they were all Pirate Factions, not even sure if I have Outlanders on my map, and if I do they're not mad at me.

They did Siege, but because -ALL- of them had melee weapons and shields, I literally walked up to their camp and killed everyone with small calibre weapons and shotguns.

**Comment by simon-82** [comment]
Yep, I am also fairly sure they must have been pirates.
That's where I did change some stuff around and that should fix it.  
Again thanks for taking the time to report stuff here and I hope you enjoy playing with the pack
