### ISSUE TITLE
Colonists use MAI recharge stations to sleep

### ISSUE THREAD

**Issue by ghost** [simon-82/ModVarietyPack#77]
Colonists use MAI recharge stations to sleep.
 The Robots need a critical red warning ore issue pop-up. I have no idea when my first MAI died.

a) colonists should be unable to claim recharge stations
b) MAI need a pop-up or red warning before they explode like the exhaustion message.
c) MAI sleep in medical bed to heal. Instead they should go to their recharge station and use plaststeel to fix themselves.

-The biggest Problem (why A is most important) you don't expect the colonists to get into the recharge station. Why would a human use that, But: The recharge Station is just a bed for game mechanic reasons.

**Comment by TLHeart** [comment]
That is from the original misc mod. Set the recharge bed to be owned by MAI, then no others can use it. MAI is another colonists and obeys the rules of the colonists.

**Comment by simon-82** [comment]
What TLHeart said. MAIs are coded as colonists. About b) and c) go ask the author of the MAI mod if he wants to change this.
