### ISSUE TITLE
Sound level of turrets

### ISSUE THREAD

**Issue by ghost** [simon-82/ModVarietyPack#78]
The Minigun and browning turret sound levels are to high. When they fire i have to adjust my sound level or mute my system. Of course that is personal preference so you are welcome to disagree.

**Comment by simon-82** [comment]
You can try to adjust them in the corresponding sound defs. Needs some tinkering though. Need to adjust, test, adjust, test... If you find values that are fine with the levels of the rest of the game, let me know. Or better, send me a pull request...

**Comment by simon-82** [comment]
levels reduced
