### ISSUE TITLE
"SBBeeb" sound missing? Also weird NullReferenceException for vomiting

### ISSUE THREAD

**Issue by Endebert** [simon-82/ModVarietyPack#8]
The exceptions happened during a raid, might be related to an enemy dying or something:

![variety_mod_error_02](https://cloud.githubusercontent.com/assets/9431420/11005291/40db2fa4-84bd-11e5-87c6-6d162d918a8a.png)

**Comment by simon-82** [comment]
Ok, so these are both related to Rimsenal Federation mod I think. 
I found the SBBeep sound is actually named only Beep so it's not found by the game. I can fix that.
And you can see the vomiting is related to Race=Bion. Bions are from Rimsenal.
I sent a pm to the mod author, maybe he can help :+1:

**Comment by simon-82** [comment]
Sound issue fixed in 1.12

**Comment by simon-82** [comment]
Still waiting on answer from the mod author. Will update the Rimsenal mod when fix is available. Closed for now.
