### ISSUE TITLE
ability to make different ciders in Brewery

### ISSUE THREAD

**Issue by Ristellise** [simon-82/ModVarietyPack#81]

**Comment by simon-82** [comment]
will I ever get to add the new ciders... sigh... :innocent:

**Comment by Ristellise** [comment]
Add the basic types of ciders : apple , pear, etc...

**Comment by Ristellise** [comment]
[Apple cider](http://store.sgwineshop.com/wp-content/uploads/2014/08/Somersby-Apple-Cider.jpg)
[Pear cider](http://deliriumcafeamsterdam.nl/wp-content/uploads/2015/04/725%20-%20Somersby%20Pear.jpg)
