### ISSUE TITLE
Ancient artifact - killbox freeze

### ISSUE THREAD

**Issue by cst89** [simon-82/ModVarietyPack#83]
Bug report: (spoiler included) When the ancient storm artifact lands and you try to build a killbox around it and then shoot it, the game completely freezes once the Invasion event triggers. Had to force exit it. I tried it several times, marking the area as "no roof", but it didn't help. The killbox was a rectangle, divided into several rooms with the artifact in the intersection of the corners ( to separate the spawned raiders ). Once I removed the walls in the radius approximately of 4 squares around the artifact, it didn't crash. Remaining walls were not a problem. Not sure if it's not an original mod bug, but as far as I remember, this trick worked in another mod.

**Comment by Karel-Kroeze** [comment]
the mechs are probably trying to find a path but not finding any, then immediately try again.

**Comment by simon-82** [comment]
You are talking about the Mechanoid Terraformer mod, right? Not the triangle artifacts? 
If so, the killbox thing might just not work with this one since it spawns pillars around it and might just bug out when you do this cheesy killbox over the spot where it wants to create a pillar.
