### ISSUE TITLE
Can not install natural grown eye on norbals.

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#84]
Have a recruited colonist that used to be a norbal. She has a bad eye, and I can not install a vat grown eye. No option in the surgery tab.

**Comment by KiotheCloud** [comment]
Yep also i tried to use developer mod and it allowed me to install it but my medic cant install cause it says "Cannot Operate colonist (needs materials even though i have the bionic part in my stack)" so plz really nid a reply for this

**Comment by simon-82** [comment]
@TLHeart just installed an eye on a norbal female
before
![1](https://cloud.githubusercontent.com/assets/14851041/12066343/cb258ce6-afe6-11e5-87a8-86ca16c57a7c.jpg)

after
![1](https://cloud.githubusercontent.com/assets/14851041/12066359/085c347a-afe7-11e5-8432-09b01cad1291.jpg)

**Comment by simon-82** [comment]
@KiotheCloud just installed advanced bionic leg on female norbal

BEFORE  
![1](https://cloud.githubusercontent.com/assets/14851041/12066394/bc9855cc-afe7-11e5-9819-edabcdb185f8.jpg)       

![1](https://cloud.githubusercontent.com/assets/14851041/12066408/ec0735ee-afe7-11e5-9564-a982152103cc.jpg)    

AFTER
![1](https://cloud.githubusercontent.com/assets/14851041/12066432/263653ee-afe8-11e5-822f-a6ce90bc55a5.jpg)

**Comment by TLHeart** [comment]
closing as it is fixed in 123.
