### ISSUE TITLE
Triangle Artifact spawn raider who can not attack.

### ISSUE THREAD

**Issue by ghost** [simon-82/ModVarietyPack#86]
"fixed bug: raiders carrying skywrath turret" was fixed in 1.20 but i encountered a single raider spawned from an artifact (the triangle thing) with that turret with the missing texture placeholder.

Also a single raider from another artifact,  this time armed but a pacifist.

Note: i am still on 1.21

**Comment by simon-82** [comment]
I thought I fixed that... Damn :cry: 

How far in the game did this happen? (year? day?)
Which faction was that guy from? And which storyteller / difficulty were you playing on?

Do you have a savegame with the guy on the map?

**Comment by simon-82** [comment]
Added high market value to the skywrath turret so it should be too expensive for any raider to have this now. Hopefully that fixes the issue now finally.

As for the pacifist spawning from an artifact. That is just a random thing that can happen,
