### ISSUE TITLE
Mechanoids struck down by Syringe

### ISSUE THREAD

**Issue by ghost** [simon-82/ModVarietyPack#88]
My doctor walked by a Scyther and sedated it with a syringe when attacked. I then tried a syringe on two centipede. They both died immediately.

Earlier i sent someone to sedate a pacifist raider. He also died from the one hit.

A syringe should only deliver one point of malee damage. For my own colonists and the Scyther one damage is shown correctly. The centipede didn't list the one damage if one damage is negated by the armor then they died because of the Anethetic.

My own animals can also be sedated but untamed animals die.

The Syther woke up again so while one should not be able to sedate a mechanoid the game mechanic worked correctly.
The syringe workes correctly on visitors.

Mod Version 1.21

**Comment by ghost** [comment]
I'm checking to see what could cause this.

**Comment by simon-82** [comment]
Seems like this can't be fixed. 
Mechs (only Centipedes) will die when their Conciousness drops to 0.1 (that's what a syringe does).

Closed for now. If @Z0MBIE2 finds / implements a fix, I'll add it to the pack.
