### ISSUE TITLE
Installation issues?

### ISSUE THREAD

**Issue by AdmiralKobi** [simon-82/ModVarietyPack#89]
Greetings!

I just came back to RimWorld with a fresh download and install of the most recent update (12d). I then downloaded and followed your instructions to install the mod pack. 

I launched RimWorld via the new RimWorld ModVariety launcher, exited the game per the instructions, then re-launched. Upon looking at the mod tab it shows a string of mods with red x's next to them. 3 of them were above the "core" and the rest were below it. 

Is that what is suppose to look like?

I tried clicking on each mod with green check mark and ended up getting an error of some kind which reverted turning them all off. Not sure where I went wrong but I re-did everything a 2nd time from scratch and the same thing happened. Help?

**Comment by simon-82** [comment]
"re-launched" with the new shortcut again, right?

**Comment by AdmiralKobi** [comment]
I found the issue. I had to launch RimWorld all by itself once and then did a full install of the modpack. Upon launching it and looking at the mod section, it now shows all the mods correctly installed on the right hand side. 

Sorry for the troubles!

**Comment by simon-82** [comment]
No problem :smile: 
If you have any issues, don't hesitate to post here!

Thanks for trying the modpack and I hope you have fun!

**Comment by AdmiralKobi** [comment]
ok, not sure what is going on but I launched it again (using the modded launcher) and I just got the same issue again... I thought it had cleared. Not sure what to do.

**Comment by simon-82** [comment]
Ok, so this is not a modded launcher. It is a shortcut to the rimworld.exe with the added option "-savedatafolder SaveData". It tells the game to look for the modsconfig.xml file (this is the file that tells the game which mods to load in what order) in _YourRimworldgamefolder_/SaveData/Config/

You have that, right?

**Comment by AdmiralKobi** [comment]
So this is what I am finding... The RimWorldVarietyPack launcher launches correctly when I use the launcher in the game folder. 

What I did was created a shortcut for that launcher to the desktop and when I try using that shortcut is when I have issues. Odd really. Either way I can now confirm that it will work as long as I use the modded launcher in the game folder itself.

**Comment by simon-82** [comment]
Ok, so by creating a shortcut for that "Launcher" (which is not a Launcher, but a Shortcut itself) you loose the properties of the file. 

Instead of creating a new shortcut, you can just move the "Launcher" to your desktop. That should work

**Comment by AdmiralKobi** [comment]
Just did that and it works great. Thanks for your super speedy help and patience... Really looking forward to getting back into the seat with this mod pack!

Cheers!

**Comment by simon-82** [comment]
One cool thing about this is that you can now choose if you want to play the modpack OR vanilla. All data for the modpack (your saves/worlds) will be in the SaveData folder. 

If you launch the game with the original exe file, you will be loaded into a vanilla game without mods. Your saves/worlds for that vanilla game will be in the usual place (...\AppData\LocalLow\Ludeon Studios\RimWorld)

**Comment by AdmiralKobi** [comment]
Good to know but for me I hate Vanilla and prefer the mod packs that provide richer and overall harder gameplay experiences. I'm confident this will do just nicely.

**Comment by simon-82** [comment]
Have fun then :smile: 
If you feel your issue is solved, you can close it yourself, ok?

**Comment by AdmiralKobi** [comment]
Oh, no problem and thanks!
