### ISSUE TITLE
Error related to hunting?

### ISSUE THREAD

**Issue by Endebert** [simon-82/ModVarietyPack#9]
In the screenshot you can see a downed Warg that a colonist wants to hunt, but instead I get a lot of exceptions:

![variety_mod_error_03](https://cloud.githubusercontent.com/assets/9431420/11005370/ac6fd6de-84bd-11e5-982e-bab75d0c2e7f.png)

My best guess is that the colonist has a weapon with a minimum range, and when he tries to hunt the downed animal (colonists usually go close for the kill), he can't find a spot where he is close enough yet above the minimum range of the weapon. But that's just wild speculation.

**Comment by simon-82** [comment]
This seems to be a tricky one. The error is coming from Ludeon code, not from any mod. 
I tried the exact same by spawning a ward ad hunting him with your guy with the same weapon. 
He gets stuck in some kind of weird loop.
I hope I can find a solution for that.

**Comment by simon-82** [comment]
Ok dude, you really have it all figured out :+1: 
It was because of the minimum range. As soon as I set the range to be min 1 square instead of min 3 squares the error goes away and the warg gets hunted :+1: 
I will do some more testing though if it's really fixed

**Comment by simon-82** [comment]
fixed in 1.12
