### ISSUE TITLE
Suggestion / Enhancement: Ability to Toggle Steam Generators On / Off

### ISSUE THREAD

**Issue by Owai-Seek** [simon-82/ModVarietyPack#92]
Generally when surviving my first winter I have to use Steam Generators, but because they use resources at a constant rate and cannot be turned off, the only current solution is to remove kindling from the hopper. A small QOL improvement would be to disable resource consumption and power output by toggling the machine on or off. This might be especially important for people who try to build in the Tundra or Ice Sheet where wood may be scarce.

Another enhancement would be the ability to uninstall small heaters as they look like they would be something moveable. It isn't something that's a huge deal, but I noticed it wasn't able to be done when I was trying to survive my first winter in -20 weather.

**Comment by simon-82** [comment]
Both good suggestions and will be included in next release :+1:
